### ISSUE TITLE
Wndows powershell 运行cmake:build的时候进程会卡着不动

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [Codesire-Deng/TemplateRepoCxx#1]
![image](https://user-images.githubusercontent.com/52443370/184354605-72b0f9aa-ea3b-47f7-89cf-5a908a22a0c5.png)

**我的解决办法：** task.json， type 键的值换成process:

```json
{
            "label": "Build the active target",
            "type": "process", // 原来是 shell
            "command": "cmake",

}
```

**Comment by Codesire-Deng** [comment]
感谢反馈，等我有windows的时候测试一下

**Comment by Codesire-Deng** [comment]
我在本地试着复现，但没有出现问题。暂时看作是 vscode 或者 shell 的 BUG。 ![image](https://user-images.githubusercontent.com/41226698/192134795-5eb967a2-c253-4f41-9484-b87d42ec2b8e.png)

**Comment by Michaelzhouisnotwhite** [comment]
> 我在本地试着复现，但没有出现问题。暂时看作是 vscode 或者 shell 的 BUG。 ![image](https://user-images.githubusercontent.com/41226698/192134795-5eb967a2-c253-4f41-9484-b87d42ec2b8e.png)

可能现在vscode版本更新了，已经距离我发问题的时间跨越了三个小版本了
